//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//MSISDNSET")]
        public string rowXPath {
            get {
                return ((string)(this["rowXPath"]));
            }
            set {
                this["rowXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//MSISDN")]
        public string phoneXPath {
            get {
                return ((string)(this["phoneXPath"]));
            }
            set {
                this["phoneXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//MSISDNROW[CHARGE_TYPE = \'Абонплата\']/CHARGE_SUM")]
        public string telServeXPhath {
            get {
                return ((string)(this["telServeXPhath"]));
            }
            set {
                this["telServeXPhath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//MSISDNROW[CHARGE_GROUP = \'Итого начисления\']/CHARGE_SUM")]
        public string callServeXPath {
            get {
                return ((string)(this["callServeXPath"]));
            }
            set {
                this["callServeXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//MSISDNROW[CHARGE_GROUP = \'Итого начисления\']/CHARGE_SUM")]
        public string othersServeXPath {
            get {
                return ((string)(this["othersServeXPath"]));
            }
            set {
                this["othersServeXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string summXPath {
            get {
                return ((string)(this["summXPath"]));
            }
            set {
                this["summXPath"] = value;
            }
        }
    }
}
