//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//MSISDNSET")]
        public string rowXPath {
            get {
                return ((string)(this["rowXPath"]));
            }
            set {
                this["rowXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSISDNROW/MSISDN")]
        public string phoneXPath {
            get {
                return ((string)(this["phoneXPath"]));
            }
            set {
                this["phoneXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSISDNROW[CHARGE_TYPE = \'Абонплата\']/CHARGE_SUM")]
        public string telServeXPhath {
            get {
                return ((string)(this["telServeXPhath"]));
            }
            set {
                this["telServeXPhath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//MSISDNROW[CHARGE_GROUP = \'Итого начисления\']/CHARGE_SUM")]
        public string callServeXPath {
            get {
                return ((string)(this["callServeXPath"]));
            }
            set {
                this["callServeXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//MSISDNROW[CHARGE_GROUP = \'Итого начисления\']/CHARGE_SUM")]
        public string othersServeXPath {
            get {
                return ((string)(this["othersServeXPath"]));
            }
            set {
                this["othersServeXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSISDNROW[CHARGE_GROUP = \'Итого начисления\']/CHARGE_SUM")]
        public string summXPath {
            get {
                return ((string)(this["summXPath"]));
            }
            set {
                this["summXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//CLIENTROW")]
        public string clientsRowXPath {
            get {
                return ((string)(this["clientsRowXPath"]));
            }
            set {
                this["clientsRowXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSISDNROW/CLNT_ID")]
        public string clientIdXPath {
            get {
                return ((string)(this["clientIdXPath"]));
            }
            set {
                this["clientIdXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSISDNROW/NAME")]
        public string clientNameXPath {
            get {
                return ((string)(this["clientNameXPath"]));
            }
            set {
                this["clientNameXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OB_SDATE")]
        public string clientStartXPath {
            get {
                return ((string)(this["clientStartXPath"]));
            }
            set {
                this["clientStartXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OB_EDATE")]
        public string clientEndXPath {
            get {
                return ((string)(this["clientEndXPath"]));
            }
            set {
                this["clientEndXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHARGE_GROUP")]
        public string groupXPath {
            get {
                return ((string)(this["groupXPath"]));
            }
            set {
                this["groupXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHARGE_TYPE")]
        public string typeXPath {
            get {
                return ((string)(this["typeXPath"]));
            }
            set {
                this["typeXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSISDNROW")]
        public string dataRowXPath {
            get {
                return ((string)(this["dataRowXPath"]));
            }
            set {
                this["dataRowXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHARGE_SUM")]
        public string valueXPath {
            get {
                return ((string)(this["valueXPath"]));
            }
            set {
                this["valueXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KOLVO")]
        public string countXPath {
            get {
                return ((string)(this["countXPath"]));
            }
            set {
                this["countXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ED_IZM")]
        public string measureXPath {
            get {
                return ((string)(this["measureXPath"]));
            }
            set {
                this["measureXPath"] = value;
            }
        }
    }
}
